#!/usr/bin/env python3
"""Generate feeds.opml from config/feeds.json (canonical source)."""

import json
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

SRC_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SRC_DIR.parent
CONFIG_PATH = PROJECT_DIR / "config" / "feeds.json"
OPML_PATH = PROJECT_DIR / "feeds.opml"

NS = "https://codeberg.org/r-Kai/FengWen"
CODEBERG_BASE = "https://codeberg.org/r-Kai/FengWen/raw/branch/main/feeds"


def build_opml(config):
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<opml version="2.0" xmlns:fw="{NS}">',
        '  <head>',
        '    <title>Feng Wen (风闻) — AI/Tech News Feeds</title>',
        f'    <dateCreated>{datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}</dateCreated>',
        '    <ownerName>Feng Wen</ownerName>',
        '  </head>',
        '  <body>',
        '    <!--',
        '      fw:type values:',
        '        "created" = scraped/generated by Feng Wen, hosted on Codeberg',
        '        "official" = official RSS/Atom feed from the source',
        '    -->',
    ]

    category_feeds: dict[str, list[str]] = {}

    # Collect created feeds
    for entry in config.get("created", []):
        cat_key = entry.get("category", "Uncategorized")
        for page in entry.get("pages", []):
            xml_url = f"{CODEBERG_BASE}/{page['output_file']}"
            category_feeds.setdefault(cat_key, []).append(
                f'      <outline text="{escape(page["label"])}" title="{escape(page["label"])}" type="rss" '
                f'xmlUrl="{escape(xml_url)}" htmlUrl="{escape(page["url"])}" fw:type="created"/>'
            )

    # Collect official feeds
    for entry in config.get("official", []):
        cat_key = entry.get("category", "Uncategorized")
        category_feeds.setdefault(cat_key, []).append(
            f'      <outline text="{escape(entry["name"])}" title="{escape(entry["name"])}" type="rss" '
            f'xmlUrl="{escape(entry["xmlUrl"])}" htmlUrl="{escape(entry["htmlUrl"])}" fw:type="official"/>'
        )

    # Emit categories in alphabetical order
    for cat_key in sorted(category_feeds.keys()):
        lines.append(f'    <outline text="{escape(cat_key)}" title="{escape(cat_key)}">')
        for feed_line in category_feeds[cat_key]:
            lines.append(feed_line)
        lines.append('    </outline>')

    lines.append('  </body>')
    lines.append('</opml>')
    return '\n'.join(lines) + '\n'


def main():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        config = json.load(f)
    opml = build_opml(config)
    OPML_PATH.write_text(opml, encoding="utf-8")
    print(f"Written {OPML_PATH}")


if __name__ == "__main__":
    main()
